language: node_js
node_js:
  - 0.12
  - 4
  - 5
branches:
  only:
    - master
    - active
    - test
install: npm i
notifications:
  email:
    recipients:
      - om@soundsapiens.com
    on_success: change
    on_failure: always
